OPENAI_URL = 'http://localhost:8080/v1'
OPENAI_API_KEY = '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'
CONFLUENCE_URL = 'https://spursol.atlassian.net/wiki'
CONFLUENCE_USERNAME = 'mohammad.saad@spursol.com'
CONFLUENCE_API_TOKEN = 'ATATT3xFfGF0pcuPNFZGsrqvdY-EENslQdpYA7JwJtR2FjCf5F8qSHQIfwzHs_M28sU4EYk4nco9P3y0lg1JDy3538Ho7BvL7Eh_Py339zMKqbtxrw8iEo7WT22Ajy1wrbsKC4LId_SNlSQLtvVXWbjwDFqRHm7XPojDnpkMhMqNZh9VBxX85O0=A1791CB9'